% ±‡“ÎœÓƒø
frameworkpath = fullfile(cd, 'CTP_FRAMEWORK');
boostPath = 'E:\boost_1_55_0_32';
mongoPath = 'E:\mongo-cxx-driver-32';

mex(['-I', frameworkpath], ... 
    fullfile(['-I', frameworkpath], 'ThostTraderApi'), ...
    fullfile(['-L', frameworkpath], 'ThostTraderApi'), ...
    fullfile(['-I', boostPath]),...
    fullfile(['-L', boostPath], 'lib32-msvc-12.0'),...
    fullfile(['-I', mongoPath], 'include'),...
    fullfile(['-L', mongoPath], 'lib'),...
    '-lws2_32.lib',...
    '-lthostmduserapi.lib', ...
    '-lthosttraderapi.lib', ...
    '-lmongoclient-gd.lib', ...
    '-lmongoclient.lib', ...
    '-lboost_chrono-vc120-mt-1_55.lib', ...
    '-lboost_date_time-vc120-mt-1_55.lib', ...
    '-lboost_regex-vc120-mt-1_55.lib', ...
    '-lboost_system-vc120-mt-1_55.lib', ...
    '-lboost_thread-vc120-mt-1_55.lib', ...
    'TraderMain.cpp', ...
    'CTP_FRAMEWORK\TraderApi.cpp', ...
    'CTP_FRAMEWORK\toolkit.cpp', ...
    'CTP_FRAMEWORK\MdUserApi.cpp', ...
    'CTP_FRAMEWORK\FunctionCallBackSet.cpp', ...
    'CTP_FRAMEWORK\CTPMsgQueue.cpp');
clear frameworkpath boostPath mongoPath
