% ±‡“ÎœÓƒø
mex -IE:\workplace\CTP_MATLAB_MEX\CTP_FRAMEWORK...
    -IE:\workplace\CTP_MATLAB_MEX\CTP_FRAMEWORK\ThostTraderApi...
    -LE:\workplace\CTP_MATLAB_MEX\CTP_FRAMEWORK\ThostTraderApi...
    -lthostmduserapi.lib...
    -lthosttraderapi.lib...
    TraderMain.cpp...
    CTP_FRAMEWORK\TraderApi.cpp...
    CTP_FRAMEWORK\toolkit.cpp...
    CTP_FRAMEWORK\MdUserApi.cpp...
    CTP_FRAMEWORK\FunctionCallBackSet.cpp...
    CTP_FRAMEWORK\CTPMsgQueue.cpp
